### Scale 스케일링
- scale(x) : 같은 column끼리 z = (x - u) / s 수행함.
- minmax_scale(x)
```
instance.fit()# 계수 추정
instance.transform()# 자료 변환
instance.fit_transform()# 계수 추정, 자료 변환
```
- StandardScaler().fit_transform(data): z = (x - u) / s 에 따라 표준정규분포로 정규화

### Normalize 노멀라이징
- normalize(x): 하나의 row(벡터)의 길이(norm)이 무조건 1.0이 되도록 = 개별 데이터의 크기를 모두 같게 만드는 변환이다. 

### OneHotEncoder 
- OneHotEncoder().fit_transfrom(data): 원핫인코딩 변환

### LabelEncoder
- LabelEncoder().fit_transfrom(data): 숫자 인덱스로 변환

### Binarizer
- Binarizer(threshold=0).fit_transform(data): threshold 초과 여부에 따라 0,1로 변환

In [5]:
from sklearn.preprocessing import *
import numpy as np
import pandas as pd

In [27]:
x = (np.arange(10, dtype=np.float) - 3).reshape(-1, 1)
df = pd.DataFrame(np.hstack([x, scale(x), robust_scale(x), minmax_scale(x), maxabs_scale(x), normalize(x), Normalizer().fit_transform(x)]),
                 columns=["x", "scale(x)", "robust_scale(x)", "minmax_scale(x)", "maxabs_scale(x)", "normalize(x)","d"])
df

C:\Users\USER-PC\AppData\Local\Temp/ipykernel_26572/536568765.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = (np.arange(10, dtype=np.float) - 3).reshape(-1, 1)


x  scale(x)  robust_scale(x)  minmax_scale(x)  maxabs_scale(x)  \
0 -3.0 -1.566699        -1.000000         0.000000        -0.500000   
1 -2.0 -1.218544        -0.777778         0.111111        -0.333333   
2 -1.0 -0.870388        -0.555556         0.222222        -0.166667   
3  0.0 -0.522233        -0.333333         0.333333         0.000000   
4  1.0 -0.174078        -0.111111         0.444444         0.166667   
5  2.0  0.174078         0.111111         0.555556         0.333333   
6  3.0  0.522233         0.333333         0.666667         0.500000   
7  4.0  0.870388         0.555556         0.777778         0.666667   
8  5.0  1.218544         0.777778         0.888889         0.833333   
9  6.0  1.566699         1.000000         1.000000         1.000000   

   normalize(x)    d  
0          -1.0 -1.0  
1          -1.0 -1.0  
2          -1.0 -1.0  
3           0.0  0.0  
4           1.0  1.0  
5           1.0  1.0  
6           1.0  1.0  
7           1.0  1.0  
8           1.0  1.0  
9           1.0  1.0

In [15]:
from sklearn.datasets import load_iris
iris = load_iris()

data1 = iris.data
data2 = scale(iris.data)

scaler = StandardScaler()
scaler.fit(data1)
data2 = scaler.transform(data1)
data1.std(), data2.std()

(1.9738430577598278, 1.0)

In [31]:
lst=np.array([-20,-19,-18,-17,-16])
(lst-np.mean(lst))/np.std(lst)

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [33]:
x = np.vstack([np.arange(5, dtype=float) - 20, np.arange(5, dtype=float) - 2]).T
y1 = scale(x)
y2 = normalize(x)

print("original x:\n", x)
print("scale:\n", y1)
print("norms (scale)\n", np.linalg.norm(y1, axis=1))
print("normlize:\n", y2)
print("norms (normalize)\n", np.linalg.norm(y2, axis=1))

original x:
 [[-20.  -2.]
 [-19.  -1.]
 [-18.   0.]
 [-17.   1.]
 [-16.   2.]]
scale:
 [[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]
norms (scale)
 [2. 1. 0. 1. 2.]
normlize:
 [[-0.99503719 -0.09950372]
 [-0.99861783 -0.05255883]
 [-1.          0.        ]
 [-0.99827437  0.05872202]
 [-0.99227788  0.12403473]]
norms (normalize)
 [1. 1. 1. 1. 1.]


In [35]:
ohe = OneHotEncoder()
X = np.array([[0], [1], [5]])
ohe.fit_transform(X).toarray()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
le = LabelEncoder()
le.fit_transform(["paris", "paris", "tokyo", "amsterdam"])

array([1, 1, 2, 0], dtype=int64)

In [40]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]
Binarizer(threshold=1).fit_transform(X)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])