# 텐서플로를 사용하는 방법(tf.Tensor)

- `tf.constant([[1,2,3],[4,5,6]])`
- 계산
  - `tf.square(t)` 
  - `t@tf.transpose(t)` 
  - `tf.add(t,t), tf.multiply(t,t), tf.square(t), tf.exp(t), tf.sqrt(t)`
  - `tf.reduce_sum(t), tf.reduce_mean(t), tf.reduce_max(t), tf.math.log(t)`
- 형식변경
  - `tf.constant(a), t.numpy(), np.array(t), tf.square(a), np.square(t)`
- 타입 변경
  - `tf.constant(40., dtype=tf.float64)`
- 문자열
```
tf.constant(b"hello")
tf.constant("hello")
enc=tf.strings.unicode_encode(tf.constant([ord(c) for c in "hello"]),"UTF-8")
dec=tf.strings.unicode_decode(enc, "UTF-8")
```

- 희소 텐서 `tf.SparseTensor()`
- to_dense `tf.sparse.to_dense(t)` : 희소 텐서를 실제 텐서 형태로 리턴해줌 (0 채워서)
```
t = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])
print(t)
print(tf.sparse.to_dense(t))
```
- 집합 `tf.sets.union(tensor1,tensor2)`, `tf.sets.intersection(tensor1,tensor2)`, `tf.sets.difference(tensor1,tensor2)`
  
# 인덱싱 하는법
- `...`와 `:`는 같은 효과이다.
```
t=tf.constant([[1,2,3],[4,5,6]])

print(t[:,1:])
print(t[...,1:])

```
- 인덱싱할 때 `tf.newaxis` 넣으면 1차원을 늘릴수가 있다. 
```
t=tf.constant([[1,2,3],[4,5,6]])

t[:,:].shape, t[:,:,tf.newaxis].shape #(2,3) -> (2,3,1)
t[:,1].shape, t[:,1,tf.newaxis].shape #(2) -> (2,1)
t[1,:].shape, t[tf.newaxis,1,:].shape #(3) -> (1,3)
```

# tf.Variable
- 변수에 해당하는 Variable은 변숫값을 함부러 바꾸지 못하고, v.assign을 통해 바꿀 수 있다. 
```
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v.assign(2*v)
```
- 그 외 `v.assign_add()`, `v.assign_sub()`


In [1]:
import tensorflow as tf

t=tf.constant([[1,2,3],[4,5,6]])


In [2]:
t[:,1:],t[...,1:]

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [5, 6]])>)

In [15]:
t=tf.constant([[1,2,3],[4,5,6]])
new=t[:,:,tf.newaxis] #
t[:,:].shape, t[:,:,tf.newaxis].shape #(2,3) -> (2,3,1)
t[:,1].shape, t[:,1,tf.newaxis].shape #(2) -> (2,1)
t[1,:].shape, t[tf.newaxis,1,:].shape #(3) -> (1,3)

(TensorShape([3]), TensorShape([1, 3]))