In [2]:
import tensorflow as tf

# 텐서플로를 사용하는 방법(tf.Tensor)

- 평범한 텐서
  - `tf.constant([[1,2,3],[4,5,6]])`
- 계산
  - `tf.square(t)` 
  - `t@tf.transpose(t)` 
  - `tf.add(t,t), tf.multiply(t,t), tf.square(t), tf.exp(t), tf.sqrt(t)`
  - `tf.reduce_sum(t), tf.reduce_mean(t), tf.reduce_max(t), tf.math.log(t)`
- 형식변경
  - `tf.constant(a), t.numpy(), np.array(t), tf.square(a), np.square(t)`
- 타입 변경
  - `tf.constant(40., dtype=tf.float64)`
- 문자열
  - `tf.constant(b"hello")`
  - `tf.constant("hello")`
  - `enc=tf.strings.unicode_encode(tf.constant([ord(c) for c in "hello"]),"UTF-8")`
  - `dec=tf.strings.unicode_decode(enc, "UTF-8")`

- 희소 텐서 `tf.SparseTensor()`
- to_dense `tf.sparse.to_dense(t)` : 희소 텐서를 실제 텐서 형태로 리턴해줌 (0 채워서)

In [6]:
t = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])
print(t)
print(tf.sparse.to_dense(t))

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]], shape=(3, 4), dtype=float32)


- 집합 `tf.sets.union(tensor1,tensor2)`, `tf.sets.intersection(tensor1,tensor2)`, `tf.sets.difference(tensor1,tensor2)`
  
# 인덱싱 하는법
- `...`와 `:`는 같은 효과이다.

In [3]:
t=tf.constant([[1,2,3],[4,5,6]])
print(t[:,1:])
print(t[...,1:])

tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [5 6]], shape=(2, 2), dtype=int32)


- 인덱싱할 때 `tf.newaxis` 넣으면 1차원을 늘릴수가 있다. 

In [4]:
t=tf.constant([[1,2,3],[4,5,6]])

t[:,:].shape, t[:,:,tf.newaxis].shape #(2,3) -> (2,3,1)
t[:,1].shape, t[:,1,tf.newaxis].shape #(2) -> (2,1)
t[1,:].shape, t[tf.newaxis,1,:].shape #(3) -> (1,3)

(TensorShape([3]), TensorShape([1, 3]))

# tf.Variable
- 변수에 해당하는 Variable은 변숫값을 함부러 바꾸지 못하고, v.assign을 통해 바꿀 수 있다. 
- 그 외 `v.assign_add()`, `v.assign_sub()` 

In [5]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>