In [1]:
# 파이썬 ≥3.5 필수
import sys
assert sys.version_info >= (3, 5)

# 사이킷런 ≥0.20 필수
import sklearn
assert sklearn.__version__ >= "0.20"

# 텐서플로 ≥2.0 필수
import tensorflow as tf
assert tf.__version__ >= "2.0"

from tensorflow import keras

# 공통 모듈 임포트
import numpy as np
import os

# 노트북 실행 결과를 동일하게 유지하기 위해
np.random.seed(42)

# 깔끔한 그래프 출력을 위해
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# 그림을 저장할 위치
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "ann"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("그림 저장:", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [ ]:
#사용자 정의 레이어
class MyLayer(keras.layers.layer):
    def __init__(self, **kwargs):
        pass
    
    def build(self):
        pass
    
    def call(self,X):
        return #출력값을 리턴함

In [8]:
d=['a','b','c','d']
slook=tf.keras.layers.StringLookup(vocabulary=d)
slook(['a','a','d','d'])

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 1, 4, 4])>

In [15]:
norm=tf.keras.layers.Normalization(axis=1)
norm.adapt(tf.constant([[1.4,3.2],[4.1,5.5]]))
norm

In [22]:
adapt_data = np.array([[0., 7., 4.],
                       [2., 9., 6.],
                       [0., 7., 4.],
                       [2., 9., 6.]], dtype='float32')
input_data = np.array([[0., 7., 4.]], dtype='float32')
layer = tf.keras.layers.Normalization(axis=1)
layer.adapt(adapt_data)
layer(input_data)

layer = tf.keras.layers.Normalization(axis=1)
layer.adapt([[1,2,3],[4,5,6]])
layer([[7,8,9]])

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[3., 3., 3.]], dtype=float32)>

In [24]:
layer = tf.keras.layers.Normalization(axis=None)
layer.adapt([1,2,3,4,5])
layer([6,7]),layer([1,2,3,4,5])

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.1213205, 2.828427 ], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=
 array([-1.4142135 , -0.70710677,  0.        ,  0.70710677,  1.4142135 ],
       dtype=float32)>)

In [29]:
layer